
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ideasdb
      POSTGRES_USER: ideauser
      POSTGRES_PASSWORD: ideapass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: